---
- name: Install Kopia and restore backup
  hosts: 127.0.0.1
  become: yes
  vars_prompt:
    - name: "aws_access_key"
      prompt: "Enter AWS Access Key ID"
      private: yes
    - name: "aws_secret_key"
      prompt: "Enter AWS Secret Access Key"
      private: yes
    - name: "kopia_password"
      prompt: "Enter password for the Kopia repository"
      private: yes

  tasks:
    - name: Install dependencies
      package:
        name:
          - curl
        state: present

    - name: Download Kopia
      become: yes
      shell: |
        sudo rpm --import https://kopia.io/signing-key
    - name: Add Kopia repository
      copy:
        dest: /etc/yum.repos.d/kopia.repo
        content: |
          [Kopia]
          name=Kopia
          baseurl=http://packages.kopia.io/rpm/stable/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=https://kopia.io/signing-key
    - name: Install Kopia
      become: yes
      shell: |
        sudo dnf install -y kopia
          
